
// This file has been generated by the GUI designer. Do not modify.
namespace CupboardDesigner
{
	public partial class Order
	{
		private global::Gtk.Notebook notebook1;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Table table3;
		private global::Gtk.ComboBox comboBasis;
		private global::Gtk.ComboBox comboCubeH;
		private global::Gtk.ComboBox comboCubeV;
		private global::QSWidgetLib.DatePicker dateArrval;
		private global::QSWidgetLib.DatePicker dateDelivery;
		private global::Gtk.Entry entryCustomer;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView textviewComments;
		private global::Gtk.Label label1;
		private global::Gtk.Label label10;
		private global::Gtk.Label label11;
		private global::Gtk.Label label12;
		private global::Gtk.Label label13;
		private global::Gtk.Label label2;
		private global::Gtk.Label label3;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TreeView treeviewComponents;
		private global::Gtk.Label label7;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Label labelInfo;
		private global::Gtk.HBox hbox3;
		private global::Gtk.DrawingArea drawCupboard;
		private global::Gtk.ScrolledWindow scrolledCubeList;
		private global::Gtk.Label label8;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CupboardDesigner.Order
			this.Name = "CupboardDesigner.Order";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child CupboardDesigner.Order.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 1;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.table3 = new global::Gtk.Table (((uint)(4)), ((uint)(4)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.comboBasis = new global::Gtk.ComboBox ();
			this.comboBasis.Name = "comboBasis";
			this.table3.Add (this.comboBasis);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table3 [this.comboBasis]));
			w2.LeftAttach = ((uint)(3));
			w2.RightAttach = ((uint)(4));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.comboCubeH = global::Gtk.ComboBox.NewText ();
			this.comboCubeH.AppendText (global::Mono.Unix.Catalog.GetString ("1"));
			this.comboCubeH.AppendText (global::Mono.Unix.Catalog.GetString ("2"));
			this.comboCubeH.AppendText (global::Mono.Unix.Catalog.GetString ("3"));
			this.comboCubeH.AppendText (global::Mono.Unix.Catalog.GetString ("4"));
			this.comboCubeH.AppendText (global::Mono.Unix.Catalog.GetString ("5"));
			this.comboCubeH.AppendText (global::Mono.Unix.Catalog.GetString ("6"));
			this.comboCubeH.AppendText (global::Mono.Unix.Catalog.GetString ("7"));
			this.comboCubeH.AppendText (global::Mono.Unix.Catalog.GetString ("8"));
			this.comboCubeH.AppendText (global::Mono.Unix.Catalog.GetString ("9"));
			this.comboCubeH.AppendText (global::Mono.Unix.Catalog.GetString ("10"));
			this.comboCubeH.Name = "comboCubeH";
			this.comboCubeH.Active = 0;
			this.table3.Add (this.comboCubeH);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table3 [this.comboCubeH]));
			w3.TopAttach = ((uint)(2));
			w3.BottomAttach = ((uint)(3));
			w3.LeftAttach = ((uint)(3));
			w3.RightAttach = ((uint)(4));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.comboCubeV = global::Gtk.ComboBox.NewText ();
			this.comboCubeV.AppendText (global::Mono.Unix.Catalog.GetString ("1"));
			this.comboCubeV.AppendText (global::Mono.Unix.Catalog.GetString ("2"));
			this.comboCubeV.AppendText (global::Mono.Unix.Catalog.GetString ("3"));
			this.comboCubeV.AppendText (global::Mono.Unix.Catalog.GetString ("4"));
			this.comboCubeV.AppendText (global::Mono.Unix.Catalog.GetString ("5"));
			this.comboCubeV.AppendText (global::Mono.Unix.Catalog.GetString ("6"));
			this.comboCubeV.AppendText (global::Mono.Unix.Catalog.GetString ("7"));
			this.comboCubeV.AppendText (global::Mono.Unix.Catalog.GetString ("8"));
			this.comboCubeV.AppendText (global::Mono.Unix.Catalog.GetString ("9"));
			this.comboCubeV.AppendText (global::Mono.Unix.Catalog.GetString ("10"));
			this.comboCubeV.Name = "comboCubeV";
			this.comboCubeV.Active = 0;
			this.table3.Add (this.comboCubeV);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table3 [this.comboCubeV]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.LeftAttach = ((uint)(3));
			w4.RightAttach = ((uint)(4));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.dateArrval = new global::QSWidgetLib.DatePicker ();
			this.dateArrval.Events = ((global::Gdk.EventMask)(256));
			this.dateArrval.Name = "dateArrval";
			this.dateArrval.Date = new global::System.DateTime (0);
			this.dateArrval.IsEditable = true;
			this.dateArrval.AutoSeparation = true;
			this.table3.Add (this.dateArrval);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table3 [this.dateArrval]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.dateDelivery = new global::QSWidgetLib.DatePicker ();
			this.dateDelivery.Events = ((global::Gdk.EventMask)(256));
			this.dateDelivery.Name = "dateDelivery";
			this.dateDelivery.Date = new global::System.DateTime (0);
			this.dateDelivery.IsEditable = true;
			this.dateDelivery.AutoSeparation = true;
			this.table3.Add (this.dateDelivery);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table3 [this.dateDelivery]));
			w6.TopAttach = ((uint)(2));
			w6.BottomAttach = ((uint)(3));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entryCustomer = new global::Gtk.Entry ();
			this.entryCustomer.CanFocus = true;
			this.entryCustomer.Name = "entryCustomer";
			this.entryCustomer.IsEditable = true;
			this.entryCustomer.InvisibleChar = '●';
			this.table3.Add (this.entryCustomer);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table3 [this.entryCustomer]));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textviewComments = new global::Gtk.TextView ();
			this.textviewComments.CanFocus = true;
			this.textviewComments.Name = "textviewComments";
			this.GtkScrolledWindow.Add (this.textviewComments);
			this.table3.Add (this.GtkScrolledWindow);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table3 [this.GtkScrolledWindow]));
			w9.TopAttach = ((uint)(3));
			w9.BottomAttach = ((uint)(4));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 1F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Тип шкафа<span foreground=\"red\">*</span>:");
			this.label1.UseMarkup = true;
			this.table3.Add (this.label1);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table3 [this.label1]));
			w10.LeftAttach = ((uint)(2));
			w10.RightAttach = ((uint)(3));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Клиент:");
			this.table3.Add (this.label10);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table3 [this.label10]));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Дата прихода:");
			this.table3.Add (this.label11);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table3 [this.label11]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Дата сдачи:");
			this.table3.Add (this.label12);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table3 [this.label12]));
			w13.TopAttach = ((uint)(2));
			w13.BottomAttach = ((uint)(3));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Комментарии:");
			this.table3.Add (this.label13);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table3 [this.label13]));
			w14.TopAttach = ((uint)(3));
			w14.BottomAttach = ((uint)(4));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 1F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Кубов по вертикали<span foreground=\"red\">*</span>:");
			this.label2.UseMarkup = true;
			this.table3.Add (this.label2);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table3 [this.label2]));
			w15.TopAttach = ((uint)(1));
			w15.BottomAttach = ((uint)(2));
			w15.LeftAttach = ((uint)(2));
			w15.RightAttach = ((uint)(3));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 1F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Кубов по горизонтали<span foreground=\"red\">*</span>:");
			this.label3.UseMarkup = true;
			this.table3.Add (this.label3);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table3 [this.label3]));
			w16.TopAttach = ((uint)(2));
			w16.BottomAttach = ((uint)(3));
			w16.LeftAttach = ((uint)(2));
			w16.RightAttach = ((uint)(3));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox4.Add (this.table3);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.table3]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.treeviewComponents = new global::Gtk.TreeView ();
			this.treeviewComponents.CanFocus = true;
			this.treeviewComponents.Name = "treeviewComponents";
			this.GtkScrolledWindow1.Add (this.treeviewComponents);
			this.vbox4.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.GtkScrolledWindow1]));
			w19.Position = 1;
			this.notebook1.Add (this.vbox4);
			// Notebook tab
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Информация");
			this.notebook1.SetTabLabel (this.vbox4, this.label7);
			this.label7.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.labelInfo = new global::Gtk.Label ();
			this.labelInfo.Name = "labelInfo";
			this.labelInfo.Xalign = 0F;
			this.labelInfo.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.vbox2.Add (this.labelInfo);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.labelInfo]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.drawCupboard = new global::Gtk.DrawingArea ();
			this.drawCupboard.Name = "drawCupboard";
			this.hbox3.Add (this.drawCupboard);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.drawCupboard]));
			w22.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.scrolledCubeList = new global::Gtk.ScrolledWindow ();
			this.scrolledCubeList.CanFocus = true;
			this.scrolledCubeList.Name = "scrolledCubeList";
			this.scrolledCubeList.VscrollbarPolicy = ((global::Gtk.PolicyType)(0));
			this.scrolledCubeList.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.scrolledCubeList.ShadowType = ((global::Gtk.ShadowType)(1));
			this.hbox3.Add (this.scrolledCubeList);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.scrolledCubeList]));
			w23.Position = 1;
			w23.Expand = false;
			this.vbox2.Add (this.hbox3);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
			w24.Position = 1;
			this.notebook1.Add (this.vbox2);
			global::Gtk.Notebook.NotebookChild w25 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vbox2]));
			w25.Position = 1;
			// Notebook tab
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Конструктор");
			this.notebook1.SetTabLabel (this.vbox2, this.label8);
			this.label8.ShowAll ();
			w1.Add (this.notebook1);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(w1 [this.notebook1]));
			w26.Position = 0;
			// Internal child CupboardDesigner.Order.ActionArea
			global::Gtk.HButtonBox w27 = this.ActionArea;
			w27.Name = "dialog1_ActionArea";
			w27.Spacing = 10;
			w27.BorderWidth = ((uint)(5));
			w27.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w28 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w27 [this.buttonCancel]));
			w28.Expand = false;
			w28.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			w27.Add (this.buttonOk);
			global::Gtk.ButtonBox.ButtonBoxChild w29 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w27 [this.buttonOk]));
			w29.Position = 1;
			w29.Expand = false;
			w29.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 641;
			this.DefaultHeight = 466;
			this.Show ();
			this.comboCubeV.Changed += new global::System.EventHandler (this.OnComboCubeVChanged);
			this.comboCubeH.Changed += new global::System.EventHandler (this.OnComboCubeHChanged);
			this.comboBasis.Changed += new global::System.EventHandler (this.OnComboBasisChanged);
			this.drawCupboard.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnDrawCupboardExposeEvent);
			this.drawCupboard.SizeAllocated += new global::Gtk.SizeAllocatedHandler (this.OnDrawCupboardSizeAllocated);
			this.drawCupboard.DragMotion += new global::Gtk.DragMotionHandler (this.OnDrawCupboardDragMotion);
			this.drawCupboard.DragDrop += new global::Gtk.DragDropHandler (this.OnDrawCupboardDragDrop);
			this.drawCupboard.DragBegin += new global::Gtk.DragBeginHandler (this.OnDrawCupboardDragBegin);
			this.drawCupboard.DragDataDelete += new global::Gtk.DragDataDeleteHandler (this.OnDrawCupboardDragDataDelete);
			this.drawCupboard.MotionNotifyEvent += new global::Gtk.MotionNotifyEventHandler (this.OnDrawCupboardMotionNotifyEvent);
			this.drawCupboard.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnDrawCupboardButtonPressEvent);
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
