
// This file has been generated by the GUI designer. Do not modify.
namespace CupboardDesigner
{
	public partial class CubeListItem
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.HBox hbox1;
		private global::Gtk.DrawingArea drawCube;
		private global::Gtk.Label labelName;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CupboardDesigner.CubeListItem
			global::Stetic.BinContainer.Attach (this);
			this.Name = "CupboardDesigner.CubeListItem";
			// Container child CupboardDesigner.CubeListItem.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			this.vbox2.BorderWidth = ((uint)(6));
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.drawCube = new global::Gtk.DrawingArea ();
			this.drawCube.Name = "drawCube";
			this.hbox1.Add (this.drawCube);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.drawCube]));
			w1.Position = 0;
			w1.Fill = false;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w2.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.labelName = new global::Gtk.Label ();
			this.labelName.Name = "labelName";
			this.labelName.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.vbox2.Add (this.labelName);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.labelName]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.drawCube.ExposeEvent += new global::Gtk.ExposeEventHandler (this.OnDrawCubeExposeEvent);
			this.drawCube.DragBegin += new global::Gtk.DragBeginHandler (this.OnDrawCubeDragBegin);
		}
	}
}
